---
- name: load passwords
  include_vars: vars/passwords.yml

- name: install git
  apt:
    name: "{{ pacotes }}"
    update_cache: yes
  vars:
    pacotes:
      - git
      - curl
      - python

- name: Create user ubuntu
  user:
    name: ubuntu
    group: sudo
    comment: Create admin user
    shell: /bin/bash
    password: "{{ passwords.userpass | password_hash('sha512') }}"
    update_password: on_create

- name: create user ubuntu home path
  file:
    path: /home/ubuntu
    state: directory
    owner: ubuntu    

- name: Download and install docker  
  shell: "curl -fsSL https://get.docker.com | sh"
  args:
    chdir: /home/ubuntu
    executable: /bin/bash  

- name: Alter user
  become: yes  
  shell: "usermod -aG docker ubuntu"

- name: Download and install docker-compose
  become: yes
  shell: "curl -L \"https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose"
  args:
    chdir: /home/ubuntu
    executable: /bin/bash

- name: Alter docker-compose permission
  become: yes
  shell: "chmod +x /usr/local/bin/docker-compose"
  args:  
    executable: /bin/bash

- name: Create symbolic link for docker-compose
  file:
    src: "/usr/local/bin/docker-compose"
    name: "/usr/bin/docker-compose"
    state: link

- name: Download Pip
  become: yes
  shell: "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py"
  args:
    chdir: /home/ubuntu
    executable: /bin/bash

- name: Install Pip
  become: yes
  shell: "python get-pip.py"
  args:
    chdir: /home/ubuntu
    executable: /bin/bash
