---
- name: load passwords
  include_vars: vars/passwords.yml

- name: install git
  apt:
    name: "{{ pacotes }}"
    update_cache: yes
  vars:
    pacotes:
      - git
      - curl
      - python

- name: Create user ubuntu
  user:
    name: ubuntu
    group: sudo
    comment: Create admin user
    shell: /bin/bash
    password: "{{ passwords.userpass | password_hash('sha512') }}"
    update_password: on_create

- name: create user ubuntu home path
  file:
    path: /home/ubuntu
    state: directory
    owner: ubuntu    