---
  - name: install haproxy
    become: yes
    shell: "apt-get install haproxy -y"    

  - name: copy cfg
    become: yes
    template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

  - name: restart haproxy
    systemd:
      name: haproxy
      state: restarted
      enabled: True 