
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
	v.memory = 2048
  end

  config.vm.define "developer" do |v|
	  v.vm.network "private_network", ip: "10.20.1.4"
  end

  config.vm.provider "virtualbox" do |x|
    x.memory = 2048
  end

  config.vm.define "developer" do |x|
    x.vm.network "private_network", ip: "10.20.1.5"
  end

  config.vm.provider "virtualbox" do |z|
    z.memory = 2048
  end

  config.vm.define "developer" do |z|
    z.vm.network "private_network", ip: "10.20.1.6"
  end  
  
end